### ISSUE TITLE
Build: Could not get unknown property 'apiKey'

### ISSUE THREAD

**Issue by jQrgen** [tepungberas/mavericks-sample#1]
Hey, thanks for the sample repo. 

I get the following error when i try to build it:

```
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':app'
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'apiKey' for BuildType_Decorated{name=debug, debuggable=true, testCoverageEnabled=false, jniDebuggable=false, pseudoLocalesEnabled=false, renderscriptDebuggable=false, renderscriptOptimLevel=3, minifyEnabled=false, zipAlignEnabled=true, signingConfig=SigningConfig_Decorated{name=debug, storeFile=/Users/jqrgen/.android/debug.keystore, storePassword=android, keyAlias=AndroidDebugKey, keyPassword=android, storeType=/Users/jqrgen/.android/debug.keystore, v1SigningEnabled=true, v2SigningEnabled=true}, embedMicroApp=false, mBuildConfigFields={}, mResValues={}, mProguardFiles=[], mConsumerProguardFiles=[], mManifestPlaceholders={}} of type com.android.build.gradle.internal.dsl.BuildType.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:83)
	at org.gradle.internal.metaobject.ConfigureDelegate.getProperty(ConfigureDelegate.java:130)
	at org.codehaus.groovy.runtime.InvokerHelper.getProperty(InvokerHelper.java:174)
	at groovy.lang.Closure.getProperty(Closure.java:291)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
```

![screen shot 2018-09-24 at 21 36 40](https://user-images.githubusercontent.com/3964957/45974559-962cfe00-c039-11e8-868b-8cad18817f29.png)

Thanks

**Comment by arierie** [comment]
Hi there, it's _gradle.properties_ (local file). You need to add it first if it doesn't exist by right click on the top of the directory -> new -> file -> name it gradle.properties. After that, add this following code :
```
# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
org.gradle.jvmargs=-Xmx1536m
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
apiKey="PUT YOUR API KEY HERE"
```

**Comment by arierie** [comment]
actually, you only need to add it
`apiKey="PUT YOUR API KEY HERE"`

**Comment by jQrgen** [comment]
Thanks for the solution 💯
